// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReactorId.proto

#include "ReactorId.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace reactor {
constexpr ReactorId::ReactorId(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : reactorid_(int64_t{0}){}
struct ReactorIdDefaultTypeInternal {
  constexpr ReactorIdDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReactorIdDefaultTypeInternal() {}
  union {
    ReactorId _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReactorIdDefaultTypeInternal _ReactorId_default_instance_;
}  // namespace reactor
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ReactorId_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ReactorId_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ReactorId_2eproto = nullptr;

const uint32_t TableStruct_ReactorId_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::reactor::ReactorId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::reactor::ReactorId, reactorid_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::reactor::ReactorId)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::reactor::_ReactorId_default_instance_),
};

const char descriptor_table_protodef_ReactorId_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017ReactorId.proto\022\007reactor\"\036\n\tReactorId\022"
  "\021\n\treactorId\030\001 \001(\003b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ReactorId_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ReactorId_2eproto = {
  false, false, 66, descriptor_table_protodef_ReactorId_2eproto, "ReactorId.proto", 
  &descriptor_table_ReactorId_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_ReactorId_2eproto::offsets,
  file_level_metadata_ReactorId_2eproto, file_level_enum_descriptors_ReactorId_2eproto, file_level_service_descriptors_ReactorId_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ReactorId_2eproto_getter() {
  return &descriptor_table_ReactorId_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ReactorId_2eproto(&descriptor_table_ReactorId_2eproto);
namespace reactor {

// ===================================================================

class ReactorId::_Internal {
 public:
};

ReactorId::ReactorId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:reactor.ReactorId)
}
ReactorId::ReactorId(const ReactorId& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  reactorid_ = from.reactorid_;
  // @@protoc_insertion_point(copy_constructor:reactor.ReactorId)
}

inline void ReactorId::SharedCtor() {
reactorid_ = int64_t{0};
}

ReactorId::~ReactorId() {
  // @@protoc_insertion_point(destructor:reactor.ReactorId)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ReactorId::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReactorId::ArenaDtor(void* object) {
  ReactorId* _this = reinterpret_cast< ReactorId* >(object);
  (void)_this;
}
void ReactorId::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReactorId::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReactorId::Clear() {
// @@protoc_insertion_point(message_clear_start:reactor.ReactorId)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reactorid_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReactorId::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 reactorId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          reactorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReactorId::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:reactor.ReactorId)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 reactorId = 1;
  if (this->_internal_reactorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_reactorid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:reactor.ReactorId)
  return target;
}

size_t ReactorId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:reactor.ReactorId)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 reactorId = 1;
  if (this->_internal_reactorid() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64SizePlusOne(this->_internal_reactorid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReactorId::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ReactorId::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReactorId::GetClassData() const { return &_class_data_; }

void ReactorId::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ReactorId *>(to)->MergeFrom(
      static_cast<const ReactorId &>(from));
}


void ReactorId::MergeFrom(const ReactorId& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:reactor.ReactorId)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_reactorid() != 0) {
    _internal_set_reactorid(from._internal_reactorid());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReactorId::CopyFrom(const ReactorId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:reactor.ReactorId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReactorId::IsInitialized() const {
  return true;
}

void ReactorId::InternalSwap(ReactorId* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(reactorid_, other->reactorid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReactorId::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ReactorId_2eproto_getter, &descriptor_table_ReactorId_2eproto_once,
      file_level_metadata_ReactorId_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace reactor
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::reactor::ReactorId* Arena::CreateMaybeMessage< ::reactor::ReactorId >(Arena* arena) {
  return Arena::CreateMessageInternal< ::reactor::ReactorId >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
